### ISSUE TITLE
Hello and Old Friend

### ISSUE THREAD

**Issue by abakasam** [skhalife/calculator#17]
Hey, tried to contact you about continuous integration planning. Please contact me: 3469322511. I am from GE Healthcare.

Sam

**Comment by skhalife** [comment]
Hi @abakasam - can you send me your GE email? So we can setup a call with the account team.

**Comment by abakasam** [comment]
Found something, https://www.katalon.com .

Thanks for the replying. 
![Group-50](https://user-images.githubusercontent.com/58202540/98716888-eb2f4980-2351-11eb-8ee9-dc7e4101dde3.jpg)

Nice to see you again, HOM Center.

Sam
